### PR TITLE
Compile with OpenSSL 1.1.1a

### PR DESCRIPTION
**Pull request by yteraoka**
A compile error occurred in combination with OpenSSL 1.1.1a.
The error message is below.

I changed the order of include so that it can be compiled with OpenSSL 1.1.1a.

```
In file included from src/os/unix/ngx_process.h:12,
                 from src/core/ngx_core.h:54,
                 from /tmp/ngx_aws_auth/crypto_helper.h:5,
                 from /tmp/ngx_aws_auth/crypto_helper_openssl.c:16:
src/os/unix/ngx_setaffinity.h:16:9: error: unknown type name 'cpu_set_t'
 typedef cpu_set_t  ngx_cpuset_t;
         ^~~~~~~~~
make[1]: *** [objs/Makefile:1699: objs/addon/ngx_aws_auth/crypto_helper_openssl.o] Error 1
make: *** [Makefile:8: build] Error 2
```

### CODE REVIEW

**Comment by upstream-nsk** [comment]
I also have this problem

**Comment by shernshiou** [comment]
I can confirm this fixes the above problem. I was trying to build nginx in docker alpine with this module.

**Comment by CpuID** [comment]
confirmed this fixes my build locally, also using alpine linux

**Comment by stephenliberty** [comment]
<nudge> Another confirmation that this fixes the build issue within alpine. Please consider merging?

**Comment by hexmarkrecords** [comment]
This should be merged if not - as it resolves it for  me too
